### ISSUE TITLE
Github ssh add known hosts

### ISSUE THREAD

**Issue by Rukamakama** [TapTap21/docker-remote-deployment-action#4]
Hello,

Am trying to use this action to deploy my containers with docker-compose.
Here my `ci` file
```
  dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployments
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.DEV_HOST }}
          ssh_private_key: ${{ secrets.DEV_SSHKEY }}
          ssh_public_key: ${{ secrets.DEV_SSHKEY_PUB }}
          stack_file_name: docker-compose.yml
          docker_login_password: ${{ secrets.DIGITALOCEAN_USER }}
          docker_login_user: ${{ secrets.DIGITALOCEAN_ACCESS_PASSWORD }}
          docker_login_registry: registry.digitalocean.com
          args: up -d --build
```
This job is failing but the failure message is not clear to me. Here is the job logs
```
Registering SSH keys...
Agent pid 11
Identity added: /github/home/.ssh/id_rsa (/github/home/.ssh/id_rsa)
Add known hosts
# 1.1.1.1:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
# 1.1.1.1::22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
# 1.1.1.1::22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
# 1.1.1.1::22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
```
